config/routes.rb
Moerse::Application.routes.draw do

  match		"moerse/home", :as => "home"
  
  post		"bargains/accept"
  match		"moerse/bargains/accept", :as => "acceptBargain"
  post		"bargains/deny"
  match		"moerse/bargains/deny", :as => "denyBargain"
  post		"bargains/repropose"
  match		"moerse/bargains/repropose", :as => "reproposeBargain"
  get		"bargains/destroy"
  match		"moerse/bargains/destroy", :as => "bargain_destroy"
  resources	:bargains, :path => "/moerse/bargains"
  resources	:bargains

  resources	:products, :path => "/moerse/products"
  get		"products/destroy"
  match		"moerse/products/destroy", :as => "product_destroy"
  get		"products/destroy_real"
  match		"moerse/products/destroy_real", :as => "product_destroy_real"
  resources	:products
  
  get		"users/resetPassword"
  post		"users/resetPassword"
  match		"moerse/users/resetPassword", :as => "resetPassword"
  get		"users/dashboard"
  match		"moerse/users/dashboard", :as => "dashboard"
  get		"users/destroy_real"
  match		"moerse/users/destroy_real", :as => "user_destroy_real"
  get		"users/destroy"
  match		"moerse/users/destroy", :as => "user_destroy"
  resources	:users, :path => "/moerse/users"
  resources	:users
  
  get		"sessions/new"
  post		"sessions/create"
  get		"sessions/destroy"
  match		"moerse/sessions/destroy", :as => "logout"
  resources	:sessions, :path => "/moerse/sessions"
  resources	:sessions

  resources	:home, :path => "/moerse/home"
  resources	:home
  
  resources :imprint, :path => "/moerse/imprint"
  resources :imprint
  
  resources :agb, :path => "/moerse/agb"
  resources :agb

  root :to => "home#index"

  
end

app/models/bargain.rb
class Bargain < ActiveRecord::Base
	# bargin status: 0 = proposed, -1 = denied, 1 = accepted
	
	VORGESCHLAGEN = 0
	ABGELEHNT = -1
	AKZEPTIERT = 1
	
	validates_presence_of :product1id
	validates :product1quantity, :numericality => { :only_integer => true, :greater_than => 0 }
	validates_presence_of :product2id
	validates :product2quantity, :numericality => { :only_integer => true, :greater_than => 0 }
	
	attr_accessible :photo1, :photo2, :photo3, :photo4, :photo5, :photo6, :photo7, :photo8, :photo9, :photo10, :product1quantity, :product2quantity, :userId1, :userId2, :proposingUser, :youtube_url1, :youtube_url2, :youtube_url3, :youtube_url4, :product1id, :product2id, :status
	
	has_attached_file :photo1, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo1, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo1, :less_than => 2.megabytes
	
	has_attached_file :photo2, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo2, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo2, :less_than => 2.megabytes
	
	has_attached_file :photo3, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo3, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo3, :less_than => 2.megabytes
	
	has_attached_file :photo4, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo4, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo4, :less_than => 2.megabytes
	
	has_attached_file :photo5, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo5, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo5, :less_than => 2.megabytes
	
	has_attached_file :photo6, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo6, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo6, :less_than => 2.megabytes
	
	has_attached_file :photo7, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo7, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo7, :less_than => 2.megabytes
	
	has_attached_file :photo8, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo8, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo8, :less_than => 2.megabytes
	
	has_attached_file :photo9, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo9, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo9, :less_than => 2.megabytes
	
	has_attached_file :photo10, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename", :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension"
	validates_attachment_content_type :photo10, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo10, :less_than => 2.megabytes
	
	def product1
		return Product.find_by_id self.product1id
	end
	
	def product2
		return Product.find_by_id self.product2id
	end
	
	def owningUser1
		return User.find_by_id self.userId1
	end
	
	def owningUser2
		return User.find_by_id self.userId2
	end	
	
	def youtube_embed(youtube_url)
		if youtube_url[/youtu\.be\/([^\?]*)/]
			youtube_id = $1
		else
			# Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
			youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
			youtube_id = $5
		end
		
		return youtube_id
		#%Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
	end
end

app/controllers/bargains_controller.rb
class BargainsController < ApplicationController
	# GET /bargains
	# GET /bargains.json
	def index
		@bargains = Bargain.find(:all, :conditions => {:status => 1})
	end

	# GET /bargains/1
	def show
		@bargain = Bargain.find(params[:id])
	end

	# GET /bargains/new
	def new
		if session[:user].nil?			
			redirect_to bargains_url
			flash[:notice] = 'Sie sind nicht eingeloggt.'
		else
			@bargain = Bargain.new
			@myProducts = Product.find(:all, :conditions => ["userId = ? AND inactive != ?", session[:user].id, true])
			@otherProducts = Product.find(:all, :conditions => ["userId != ? AND inactive != ?", session[:user].id, true])
		end
	end

	# GET /bargains/1/edit
	def edit
		@bargain = Bargain.find(params[:id])
		if session[:user].nil? || (session[:user].id != @bargain.userId1 && session[:user].id != @bargain.userId2)
			redirect_to bargains_url
			flash[:notice] = 'Sie sind nicht als ein beteiligter Tauschpartner eingeloggt.'
		else
			@bargain = Bargain.find(params[:id])
			@myProducts = Product.find(:all, :conditions => ["userId = ? AND inactive != ?", session[:user].id, true])
			@otherProducts = Product.find(:all, :conditions => ["userId != ? AND inactive != ?", session[:user].id, true])
		end
	end

	# POST /bargains
	def create
		@myProducts = Product.find(:all, :conditions => ["userId = ? AND inactive != ?", session[:user].id, true]) # needed for validation redirect
		@otherProducts = Product.find(:all, :conditions => ["userId != ? AND inactive != ?", session[:user].id, true]) # needed for validation redirect
		@bargain = Bargain.new(params[:bargain])
		sendingUserProduct = @bargain.product1
		receivingUserProduct = @bargain.product2
		@bargain.userId1 = @bargain.product1.userId
		@bargain.userId2 = @bargain.product2.userId
		@bargain.status = 0
		@bargain.proposingUser = session[:user].id
		if @bargain.save
			Emailer.sendProposedBargain(User.find_by_id(@bargain.userId2), session[:user], @bargain, sendingUserProduct, receivingUserProduct).deliver
			redirect_to @bargain
			flash[:notice] = 'Der Tausch wurde erstellt und wird jetzt Ihrem Tauschpartner ' + session[:user].name + ' vorgeschlagen.'
		else
			render :new
		end
	end

  # PUT /bargains/1
  def update
    @bargain = Bargain.find(params[:id])
	if params["repropose"]
		@bargain = Bargain.find(params[:id])
		if @bargain.update_attributes(params[:bargain])
			if (@bargain.userId1 == session[:user].id)
				sender = @bargain.owningUser1
				recipient = @bargain.owningUser2
				sendingUserProduct = @bargain.product1
				receivingUserProduct = @bargain.product2
			else
				sender = @bargain.owningUser2
				recipient = @bargain.owningUser1
				sendingUserProduct = @bargain.product2
				receivingUserProduct = @bargain.product1
			end
			Emailer.reproposeBargain(recipient, sender, sendingUserProduct, receivingUserProduct).deliver
			redirect_to @bargain
			flash[:notice] = 'Der Tausch wurde modifiziert und Ihr Tauschpartner wurde benachrichtigt.'
		else
			redirect_to @bargain
			flash[:notice] = 'Etwas hat unerwarteterweise nicht geklappt. Bitte versuchen Sie es erneut.'
		end
		
	elsif params["accept"]
		@bargain = Bargain.find(params[:id])
		@bargain.update_attributes({:status => 1})
		@bargain.save
		if (@bargain.userId1 == session[:user].id)
			sender = @bargain.owningUser1
			recipient = @bargain.owningUser2
			sendingUserProduct = @bargain.product1
			receivingUserProduct = @bargain.product2
		else
			sender = @bargain.owningUser2
			recipient = @bargain.owningUser1
			sendingUserProduct = @bargain.product2
			receivingUserProduct = @bargain.product1
		end
		Emailer.acceptBargain(recipient, sender, sendingUserProduct, receivingUserProduct).deliver
		Emailer.acceptBargainToAcceptant(sender, recipient, receivingUserProduct, sendingUserProduct).deliver
		redirect_to @bargain
		flash[:notice] = 'Der Tausch wurde akzeptiert und Ihr Tauschpartner wurde benachrichtigt. Eine E-Mail mit weiteren Informationen wurde an Sie verschickt.'
		
	elsif params["deny"]
		@bargain = Bargain.find(params[:id])
		@bargain.update_attributes({:status => -1})
		@bargain.save
		if (@bargain.userId1 == session[:user].id)
			sender = @bargain.owningUser1
			recipient = @bargain.owningUser2
			sendingUserProduct = @bargain.product1
			receivingUserProduct = @bargain.product2
		else
			sender = @bargain.owningUser2
			recipient = @bargain.owningUser1
			sendingUserProduct = @bargain.product2
			receivingUserProduct = @bargain.product1
		end
		Emailer.denyBargain(recipient, sender, @bargain, sendingUserProduct, receivingUserProduct).deliver
		redirect_to bargains_url
		flash[:notice] = 'Der Tausch wurde abgelehnt und Ihr Tauschpartner wurde benachrichtigt.'
	else	
		if @bargain.update_attributes(params[:bargain])
			(1..10).each do |i|
				if params[:bargain]["delete_photo" + i.to_s] == "1"
					photo = @bargain.send("photo" + i.to_s)
					photo.destroy
					@bargain.save
				end
			end
			redirect_to @bargain
			flash[:notice] = 'Der Tausch wurde aktualisiert.'
		else
			render :edit
		end
	end
  end

  # DELETE /bargains/1
  def destroy
    @bargain = Bargain.find(params[:id])
    @bargain.destroy
	redirect_to bargains_url
  end
end

app/helpers/bargains_helper.rb
module BargainsHelper
end

app/views/bargains/_form.html.erb
<%= form_for(@bargain) do |f| %>
  <% if @bargain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bargain.errors.count, "error") %> prohibited this bargain from being saved:</h2>

      <ul>
      <% @bargain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
	<select name="bargain[product1id]" size="8">
		<% if @myProducts.count == 0 %>
			<option value="0" disabled="disabled">Sie haben keine Produkte...</option>
		<%
			else
			myProductsArray = @myProducts.map { |product| [product.name, product.id] }
		%>
			<%= options_for_select(myProductsArray, :selected => myProductsArray[0]) %>
		<% end %>
	</select>
    <%= f.number_field :product1quantity, :size => 3, :maxlength => 3 %>&nbsp;gegen&nbsp;
    <%= f.number_field :product2quantity, :size => 3, :maxlength => 3 %>
	<select name="bargain[product2id]" size="8">	
		<% otherProductsArray = @otherProducts.map { |product| [product.name, product.id] } unless @otherProducts.nil? %>
		<%= options_for_select(otherProductsArray, :selected => otherProductsArray[0]) unless @otherProducts.nil? %>
	</select>
  </div>
  <p>
	<% if @myProducts.count == 0 %>
		<%= submit_tag "Tausch erstellen", :disabled => true %>
	<% else %>
		<%= submit_tag "Tausch erstellen" %>
	<% end %>
  </p>
<% end %>

app/views/bargains/_form_deal.html.erb
<%= form_for(@bargain) do |f| %>
	<% if @bargain.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@bargain.errors.count, "error") %> prohibited this bargain from being saved:</h2>

		  <ul>
		  <% @bargain.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	<% end %>
  <input id="bargain[proposingUser]" name="bargain[proposingUser]" type="hidden" value="<%= session[:user].id %>" />
  <p>
	<b><%= link_to @bargain.product1.name, @bargain.product1 %></b>
	<%= f.number_field :product1quantity, :size => 3, :maxlength => 3 %>&nbsp;gegen&nbsp;
	<%= f.number_field :product2quantity, :size => 3, :maxlength => 3 %>
	<b><%= link_to @bargain.product2.name, @bargain.product2 %></b>
  </p>
  
  <p>
	<%= submit_tag "Tausch modifizieren", :name => "repropose" %>
	<% if (@bargain.proposingUser != session[:user].id) %>
		<%= submit_tag "Tausch akzeptieren", :name => "accept" %> <%= submit_tag "Tausch ablehnen", :name => "deny" %>
	<% end %>
  </p>
<% end %>

<% if (session[:user].id == @bargain.userId1) %>
	<p><a href="<%= url_for bargain_destroy_path(:id => @bargain.id) %>">Tausch löschen</a></p>
<% end %>

app/views/bargains/_form_finished.html.erb
<%= form_for(@bargain) do |f| %>
	<% if @bargain.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@bargain.errors.count, "error") %> prohibited this bargain from being saved:</h2>

		  <ul>
		  <% @bargain.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	<% end %>
	<input id="bargain[proposingUser]" name="bargain[proposingUser]" type="hidden" value="<%= session[:user].id %>" />
	<p>
		<b><%= link_to @bargain.product1.name, @bargain.product1 %></b>
		<%= f.number_field :product1quantity, :size => 3, :maxlength => 3, :disabled => true %>&nbsp;gegen&nbsp;
		<%= f.number_field :product2quantity, :size => 3, :maxlength => 3, :disabled => true %>
		<b><%= link_to @bargain.product2.name, @bargain.product2 %></b>
	</p>
	<h2>Tausch dokumentieren!</h2>
	<% if session[:user].id == @bargain.userId1 %>
		<p>
			<%= f.label :youtube_url1, "Link zum Youtube-Video 1" %><br />
			<%= f.text_field :youtube_url1, :size => 80 %>
		</p>
		<p>
			<%= f.label :youtube_url3, "Link zum Youtube-Video 2" %><br />
			<%= f.text_field :youtube_url3, :size => 80 %>
		</p>
	<% else %>
		<p>
		<%= f.label :youtube_url2, "Link zum Youtube-Video 1" %><br />
		<%= f.text_field :youtube_url2, :size => 80 %>
		</p>
		<p>
		<%= f.label :youtube_url4, "Link zum Youtube-Video 2" %><br />
		<%= f.text_field :youtube_url4, :size => 80 %>
		</p>
	<% end %>
	<%
		if (session[:user].id == @bargain.userId1)
			i = 1
			start = 1
		else
			i = 5
			start = 5
		end
		while i < start + 5  do
			if @bargain.send("photo#{i}").present?
				photo = @bargain.send("photo#{i}")
	%>
				<p>
					<%= f.label "photo" + i.to_s, "Foto" %><br />
					<%= link_to image_tag(photo.url(:thumb)), photo.url(:original) %>
					<input name="bargain[delete_photo<%= i %>]" type="hidden" value="0" /><input id="user_gotSample" name="bargain[delete_photo<%= i %>]" type="checkbox" value="1" /> löschen
				</p>
			<% else %>
				<p>
					<%= f.label "photo" + i.to_s, "Foto" %><br />
					<%= f.file_field "photo" + i.to_s %>
				</p>
	 <%
			end
			i +=1
		end
	%>
	<p><%= submit_tag "Tausch dokumentieren", :name => "save" %></p>
<% end %>

<% if (session[:user].id == @bargain.userId1) %>
	<p>Dieser Tausch ist schon abgeschlossen. Du kannst ihn nicht mehr löschen.</p>
<% end %>

app/views/bargains/edit.html.erb
<h1>Tausch bearbeiten!</h1>
  
<% if @bargain.status < 1 %>
	<%= render 'form_deal' %>
<% else %>
	<%= render 'form_finished' %>
<% end %>

<p><%= link_to 'Tausch zeigen', @bargain %></p>

<br/><br/>
<% if session[:user].id == 1 %>
	<p><a href="<%= url_for bargain_destroy_path(:id => @bargain.id) %>">ALS ADMINISTRATOR LÖSCHEN</a></p>
<% end %>

app/views/bargains/index.html.erb
<h1>Alle Tausche!</h1>
<% if session[:user] %>
	<p><%= link_to 'Tausch vorschlagen', new_bargain_path %></p>
<% end %>
<table>
  <tr>
    <th>Produkt 1</th>
    <th>x</th>
    <td>gegen</td>
    <th>x</th>
    <th>Produkt 2</th>
  </tr>

<% @bargains.each do |bargain| %>
  <tr>
    <td><%= (Product.find_by_id(bargain.product1id)).name %></td>
    <td><%= bargain.product1quantity %></td>
	
    <td>&nbsp;</td>
	
    <td><%= bargain.product2quantity %></td>
    <td><%= (Product.find_by_id(bargain.product2id)).name %></td>
    <td><%= link_to 'zeigen', bargain %></td>
  </tr>
<% end %>
</table>

<br />

<% if session[:user] %>
	<p><%= link_to 'Tausch vorschlagen', new_bargain_path %></p>
<% else %>
	<p>Bitte logge dich ein um Produkte tauschen zu können!</p>
<% end %>

<br />

app/views/bargains/new.html.erb
<h1>Tausch vorschlagen!</h1>
<%= render 'form' %>

app/views/bargains/show.html.erb
<div style="float: left; display: block; width: 300px">
	<div style="height: 150px; position: relative">
		<div style="; position: absolute; bottom: 0">
			<% if @bargain.owningUser1.photo.present? %>
				  <%= image_tag @bargain.owningUser1.photo.url(:thumb) %>
			<% else %>
				<%= image_tag "/images/dummy_user.jpg", {:height => 130} %>
			<% end %>
			<a href="<%= url_for :action => :show, :controller => :users, :id => @bargain.userId1 %>"><%= @bargain.owningUser1.name %></a>
		</div>
	</div>
	<br/>

	<div class="bargain-link">
		<a href="<%= url_for :action => :show, :controller => :products, :id => @bargain.product1.id %>"><%= @bargain.product1quantity %>x
			<span class="list-head"><%= @bargain.product1.name %></span><br/>
			<%= @bargain.product1.description[0..170].strip + (@bargain.product1.description.length > 170 ? "... [mehr]" : "") %>
		</a>
	</div>
</div>

<div style="float: left; margin-top: 100px;">gegen</div>

<div style="float: right; display: block; width: 300px">
	<div style="height: 150px; position: relative">
		<div style="; position: absolute; bottom: 0">
			<a href="<%= url_for :action => :show, :controller => :users, :id => @bargain.userId2 %>"><%= @bargain.owningUser2.name %></a>
			<% if @bargain.owningUser2.photo.present? %>
				  <%= image_tag @bargain.owningUser2.photo.url(:thumb) %>
			<% else %>
				<%= image_tag "/images/dummy_user.jpg", {:height => 130} %>
			<% end %>
		</div>
	</div>
	<br/>
	
	<div class="bargain-link">
		<a href="<%= url_for :action => :show, :controller => :products, :id => @bargain.product2.id %>"><%= @bargain.product2quantity %>x
			<span class="list-head"><%= @bargain.product2.name %></span><br />
			<%= @bargain.product2.description[0..170].strip + (@bargain.product2.description.length > 170 ? "... [mehr]" : "") %>
		</a>
	</div>
</div>

<div style="clear:both; padding-top: 15px;">
	<h2>Videos des Tausches!</h2>
	<% unless @bargain.youtube_url1.nil? || @bargain.youtube_url1 == "" %>
		<p><iframe title='YouTube video player' width='640' height='390' src='http://www.youtube.com/embed/<%= @bargain.youtube_embed(@bargain.youtube_url1) %>' frameborder='0' allowfullscreen></iframe></p>
	<% end %>
	<% unless @bargain.youtube_url3.nil? || @bargain.youtube_url3 == "" %>
		<p><iframe title='YouTube video player' width='640' height='390' src='http://www.youtube.com/embed/<%= @bargain.youtube_embed(@bargain.youtube_url3) %>' frameborder='0' allowfullscreen></iframe></p>
	<% end %>
	<% unless @bargain.youtube_url2.nil? || @bargain.youtube_url2 == "" %>
		<p><iframe title='YouTube video player' width='640' height='390' src='http://www.youtube.com/embed/<%= @bargain.youtube_embed(@bargain.youtube_url2) %>' frameborder='0' allowfullscreen></iframe></p>
	<% end %>
	<% unless @bargain.youtube_url4.nil? || @bargain.youtube_url4 == "" %>
		<p><iframe title='YouTube video player' width='640' height='390' src='http://www.youtube.com/embed/<%= @bargain.youtube_embed(@bargain.youtube_url4) %>' frameborder='0' allowfullscreen></iframe></p>
	<% end %>
	<% if (@bargain.youtube_url1.nil? || @bargain.youtube_url1 == "") && (@bargain.youtube_url2.nil? || @bargain.youtube_url2 == "") && (@bargain.youtube_url3.nil? || @bargain.youtube_url3 == "") && (@bargain.youtube_url4.nil? || @bargain.youtube_url4 == "")  %>
		<p>Es gibt leider noch keine Videos für diesen Tausch.</p>
	<% end %>
	
	<h2>Bilder des Tausches!</h2>
	<%
		counter = 0
		(1..10).each do |i|
			if @bargain.send("photo#{i}").present?
				photo = @bargain.send("photo#{i}")
	%>
				<p>
					<%= link_to image_tag(photo.url(:medium)), photo.url(:original) %>
				</p>
	<%
				counter += 1
			end
		end
		if counter == 0
	%>
		<p>Es gibt leider noch keine Bilder für diesen Tausch.</p>
	<% end %>
</div>

<% if session[:user] && (@bargain.userId1 == session[:user].id || @bargain.userId2 == session[:user].id) %>
	<p><%= link_to "Eigenen Tausch bearbeiten", edit_bargain_path(@bargain) %></p>
<% end %>

<% if session[:user] && session[:user].id == 1 %>
	<p><a href="<%= url_for bargain_destroy_path(:id => @bargain.id) %>">ALS ADMINISTRATOR LÖSCHEN (vorsicht!)</a></p>
<% end %>