config/routes.rb
Moerse::Application.routes.draw do

  match		"moerse/home", :as => "home"
  
  post		"bargains/accept"
  match		"moerse/bargains/accept", :as => "acceptBargain"
  post		"bargains/deny"
  match		"moerse/bargains/deny", :as => "denyBargain"
  post		"bargains/repropose"
  match		"moerse/bargains/repropose", :as => "reproposeBargain"
  get		"bargains/destroy"
  match		"moerse/bargains/destroy", :as => "bargain_destroy"
  resources	:bargains, :path => "/moerse/bargains"
  resources	:bargains

  resources	:products, :path => "/moerse/products"
  get		"products/destroy"
  match		"moerse/products/destroy", :as => "product_destroy"
  get		"products/destroy_real"
  match		"moerse/products/destroy_real", :as => "product_destroy_real"
  resources	:products
  
  get		"users/resetPassword"
  post		"users/resetPassword"
  match		"moerse/users/resetPassword", :as => "resetPassword"
  get		"users/dashboard"
  match		"moerse/users/dashboard", :as => "dashboard"
  get		"users/destroy_real"
  match		"moerse/users/destroy_real", :as => "user_destroy_real"
  get		"users/destroy"
  match		"moerse/users/destroy", :as => "user_destroy"
  resources	:users, :path => "/moerse/users"
  resources	:users
  
  get		"sessions/new"
  post		"sessions/create"
  get		"sessions/destroy"
  match		"moerse/sessions/destroy", :as => "logout"
  resources	:sessions, :path => "/moerse/sessions"
  resources	:sessions

  resources	:home, :path => "/moerse/home"
  resources	:home
  
  resources :imprint, :path => "/moerse/imprint"
  resources :imprint
  
  resources :agb, :path => "/moerse/agb"
  resources :agb

  root :to => "home#index"

  
end

app/models/user.rb
class User < ActiveRecord::Base

    attr_accessible :email, :password, :password_confirmation, :name, :photo, :salt, :views, :inactive, :gotSample, :views
	
	# validates_confirmation_of :password
	validates_presence_of :password
	validates_presence_of :email
	validates_uniqueness_of :email
	
	# attr_protected :id, :salt
	
	validates_format_of :email, :with => /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i
	
    validates_confirmation_of :password, :confirmation => true, :presence => true
	
	# has_attached_file :photo, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :url => "/moerse/:class/:attachment/:id/:style_:basename.:extension"
	#has_attached_file :photo, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :url => "/system/:attachment/:id/:style/:basename.:extension"
	has_attached_file :photo, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :url => "/moerse/system/:class/:attachment/:id/:style/:basename.:extension", :path => ":rails_root/public/system/:class/:attachment/:id/:style/:filename"
	validates_attachment_content_type :photo, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo, :less_than => 2.megabytes

	# attr_accessor :password
    before_save :encrypt_password

    def self.authenticate email, password
        user = find_by_email email
		# puts user.inspect
		# puts "USER AUTH"
		# puts password
		# puts "vs."
		# puts user.password
		# puts (BCrypt::Engine.hash_secret password, user.salt)
        if user && user.password == (BCrypt::Engine.hash_secret password, user.salt)
            return user
        else
            return false
        end
    end

    def encrypt_password
		# puts "SAVING USER: #{self.inspect}"
		# puts password.present?
        if password.present?
            self.salt = BCrypt::Engine.generate_salt
            self.password = BCrypt::Engine.hash_secret password, self.salt
			puts self.salt
			puts self.password
        end
    end
	
	def random_password(size = 10)
		chars = (('a'..'z').to_a + ('0'..'9').to_a) - %w(i o 0 1 l 0)
		return (1..size).collect{|a| chars[rand(chars.size)] }.join
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.find(:all, :conditions => ["inactive != ?", true])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @products = Product.find(:all, :conditions => ["userId = ? AND inactive != ?", @user.id, true])
    
	@bargainsProposed = Bargain.find(:all, :conditions => {:userId1 => @user.id, :status => "1"})
	@bargainsAccepted = Bargain.find(:all, :conditions => {:userId2 => @user.id, :status => "1"})
  end

  # GET /users/1
  # GET /users/1.json
  def dashboard
	if session[:user]
		@user = User.find(session[:user].id)
		@products = Product.find(:all, :conditions => ["userId = ? AND inactive != ?", @user.id, true])
		
		@bargainsProposed = Bargain.find(:all, :conditions => {:userId1 => @user.id, :status => "1"})
		@bargainsAccepted = Bargain.find(:all, :conditions => {:userId2 => @user.id, :status => "1"})
		
		@bargainsPending = Bargain.find(:all, :conditions => {:userId1 => @user.id, :status => "0"})
		@bargainsPending += Bargain.find(:all, :conditions => {:userId2 => @user.id, :status => "0"})
	else
		redirect_to home_path
		flash[:notice] = "Sind sind nicht eingeloggt."
	end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
	if session[:user].nil? 
		redirect_to @user
		flash[:notice] = "Sie sind nicht als dieser Benutzer eingeloggt."
	elsif session[:user].id != @user.id
		redirect_to @user
		flash[:notice] = "Sie sind nicht als dieser Benutzer eingeloggt."
	end
  end

	# POST /users
	# POST /users.json
	def create
		#puts "CREATING USER"
		@user = User.new(params[:user])
		@user.views = 0
		@user.inactive = false
		if @user.save
			user = User.authenticate params[:user][:email], params[:user][:password]
			if user
				Emailer.sendWelcome(@user).deliver
				session[:user] = user
				redirect_to dashboard_path
				flash[:notice] = "Das Profil wurde erfolgreich erstellt."
			else
				@user.destroy
				render :new
				flash[:notice] = 'Etwas hat unerwarteterweise nicht geklappt. Bitte versuchen Sie es erneut.'
			end
		else
			render :new
			flash[:notice] = 'Etwas hat unerwarteterweise nicht geklappt. Bitte versuchen Sie es erneut.'
		end
	end
  
	def resetPassword
		if params && params[:email] != nil
			@user = User.find_by_email(params[:email])
			if @user.present?
				newPw = random_password(12)
				@user.update_attributes({:password => newPw, :inactive => false})
				Emailer.sendPassword(params[:email], "Neues Passwort für die Mörse", newPw).deliver
				redirect_to users_path
				flash[:notice] = "Ein neues Passwort wurde generiert und an " + params[:email] + " geschickt."
			else
				redirect_to resetPassword_path
				flash[:notice] = "Kein Benutzer mit der Email-Adresse '" + params[:email] + "' gefunden."
			end
		end
	end

	# PUT /users/1
	# PUT /users/1.json
	def update
		@user = User.find(params[:id])

		if @user.update_attributes(params[:user])
			session[:user] = @user
			redirect_to @user
			flash[:notice] = "Das Benutzerkonto wurde erfolgreich aktualisiert."
		else
			render :edit
			flash[:notice] = 'Etwas hat unerwarteterweise nicht geklappt. Bitte versuchen Sie es erneut.'
		end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		@user = User.find(params[:id])
		# @user.destroy
		@user.update_attributes({:inactive => true})
		@productsToInactivate = Product.find(:all, :conditions => {:userId => @user.id})
		@productsToInactivate.each do |product|
			product.inactive = true;
			product.save
		end
		session[:user] = nil

		redirect_to users_url
		flash[:notice] = "Ihr Benutzerkonto wurde deaktiviert."
	end

	def destroy_real
		@user = User.find(params[:id])
		@productsToDestroy = Product.find(:all, :conditions => {:userId => @user.id})
		@productsToDestroy.each do |product|
			product.destroy
		end
		@user.destroy
		session[:user] = nil
		redirect_to users_url
		flash[:notice] = "User zernichtet."
	end
	
	def random_password(size = 10)
		chars = (('a'..'z').to_a + ('0'..'9').to_a) - %w(i o 0 1 l 0)
		return (1..size).collect{|a| chars[rand(chars.size)] }.join
	end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= @user.errors.count %> Fehler haben das Speichern dieses Kontos verhindert:</h2>

			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :password, "Passwort" %><br />
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation, "Passwort wiederholen" %><br />
		<%= f.password_field :password_confirmation %>
	</p>

	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	
	<p>
		<%= f.label :photo, "Foto" %><br />
		<%= f.file_field :photo %>
	</p>
	
	<p>
		<%= f.check_box :gotSample %>
		Ich habe eine Gratisprobe erhalten.
	</p>
	
	<p>
	<%= submit_tag "abschicken" %>
	</p>
<% end %>

app/views/users/_form_resetPassword.erb
<%= form_tag("resetPassword", :method => "post") do %>
  <%= label_tag(:email, "Deine E-Mail-Adresse") %><br/>
   <%= text_field_tag(:email) %><br />
  <%= submit_tag("Passwort zusenden") %>
<% end %>

app/views/users/dashboard.erb
<% if session[:first_time] && session[:first_time] == true %>
<div style="color: #DD0000">
	<p>Wir freuen uns, Sie in der moerse begrüßen zu dürfen. Ab sofort können Sie mit dem Tauschen loslegen. So einfach geht es:</p>
	<ol>
		<li>Klicken Sie auf <b>Alle Produkte</b> und klicken Sie auf <b>Produkt erstellen</b>.<br/>
			Hier können Sie Ihr Tauschprodukt eintragen, was Sie gern anbieten möchten.</li>
		<li>Nun können Sie unter <b>Alle Tausche</b> Ihre ganz persönlichen Tauschoptionen gegen Ihr erstelltes Produkt nach Belieben vorschlagen!</li>
	</ol>
</div>
<% end %>

<h1>Eigene Produkte!</h1>
<% @products.each do |product| %>  
	<div class="link-list">
		<a href="<%= url_for :action => :show, :controller => :products, :id => product.id %>">
			<span class="list-head"><%= product.name %></span><br />
			<span class="list-text"><%= product.description[0..100].strip + (product.description.length > 100 ? "... [mehr]" : "") %></span>
		</a>
	</div>
<% end %>
<% if @products.count == 0 %>
	<div class="link-list">Sie haben noch keine Produkte eingestellt.</div>
	<%= link_to 'Produkt erstellen', new_product_path %>
<% end %>
<a name="pending" /></a>
<h1>Ausstehende Tausche!</h1>
<% @bargainsPending.each do |bargain| %>
	<div class="link-list">
		<a href="<%= url_for :action => :edit, :controller => :bargains, :id => bargain.id %>">
			<span class="list-head"><%= bargain.product1.name %></span>
			<span class="list-text"><%= bargain.product1quantity %>x</span><span class="list-text">gegen</span><span class="list-text"><%= bargain.product2quantity %>x</span>
			<span class="list-head"><%= bargain.product2.name %></span>
		</a>
	</div>
<% end %>
<% if @bargainsPending.count == 0 %>
	<div class="link-list">Sie haben keine ausstehenden Tausche.</div>
	<%= link_to 'Tausch vorschlagen', new_bargain_path %>
<% end %>

<h1>Abgeschlossene Tausche!</h1>
<% @bargainsProposed.each do |bargain| %>
	<div class="link-list">
		<a href="<%= url_for :action => :edit, :controller => :bargains, :id => bargain.id %>">
			<span class="list-head"><%= bargain.product1.name %></span>
			<span class="list-text"><%= bargain.product1quantity %>x</span><span class="list-text">gegen</span><span class="list-text"><%= bargain.product2quantity %>x</span>
			<span class="list-head"><%= bargain.product2.name %></span>
		</a>
	</div>
<% end %>
<% @bargainsAccepted.each do |bargain| %>
	<div class="link-list">
		<a href="<%= url_for :action => :edit, :controller => :bargains, :id => bargain.id %>">
			<span class="list-head"><%= bargain.product1.name %></span>
			<span class="list-text"><%= bargain.product1quantity %>x</span><span class="list-text">gegen</span><span class="list-text"><%= bargain.product2quantity %>x</span>
			<span class="list-head"><%= bargain.product2.name %></span>
		</a>
	</div>
<% end %>
<% if @bargainsProposed.count + @bargainsAccepted.count == 0 %>
	<div class="link-list">Sie haben noch keinen Tausch durchgef&uuml;hrt.</div>
<% end %>

<%= link_to "Eigenes Profil bearbeiten", edit_user_path(@user) %>

app/views/users/edit.html.erb
<h1>Eigenes Konto bearbeiten!</h1>

<%= render 'form' %>

<p><a href="<%= url_for user_destroy_path(:id => @user.id) %>" data-confirm="Sind Sie sich sicher?">Konto deaktiviren</a> |

<%= link_to 'Benutzer zeigen', @user %></p>

app/views/users/index.html.erb
<h1>Alle Benutzer!</h1>

<% @users.each do |user|
	bargainsCount = Bargain.find(:all, :conditions => {:userId1 => user.id, :status => "1"}).count + Bargain.find(:all, :conditions => {:userId2 => user.id, :status => "1"}).count
	productsCount = Product.find(:all, :conditions => ["userId = ? AND inactive!= ?", user.id, true]).count	
  %>
	  <div class="user-tile">
		<div class="user-tile-bottom">
		<% if user.photo.present? %>
			<%= link_to image_tag(user.photo.url(:thumb)), user %>
		<% else %>
			<%= link_to image_tag("/images/dummy_user.jpg", {:height => 130}), user %>
		<% end %><br />
		<%= link_to user.name, user %><br />
		<%= Product.find(:all, :conditions => ["userId = ? AND inactive!= ?", user.id, true]).count %> Produkt<%= productsCount != 1 ? "e" : "" %><br />
		<%= bargainsCount %> Tausch<%= bargainsCount != 1 ? "e" : "" %>
		</div>
	  </div>
<% end %>

<p style="clear: both; margin-top: 5px"><a href="<%= url_for :action => :new, :controller => "users" %>">Registrieren</a></p>

app/views/users/new.html.erb
<h1>Benutzerkonto anlegen!</h1>

<%= render 'form' %>

app/views/users/resetPassword.erb
<h1>Passwort zurücksetzen!</h1>

<%= render 'form_resetPassword' %>

app/views/users/show.html.erb
<div style="float: right; margin-right: 45px;">
	<% if @user.photo.present? %>
		<%= link_to image_tag(@user.photo.url(:thumb)), @user.photo.url(:original) %>
	<% else %>
		<%= image_tag "/images/dummy_user.jpg", {:height => 130} %>
	<% end %>
</div>
<h1><%= @user.name %>!</h1>

<h2>Produkte</h2>
<% @products.each do |product| %>  
	<div class="link-list">
		<a href="<%= url_for :action => :show, :controller => :products, :id => product.id %>">
			<span class="list-head"><%= product.name %></span><br />
			<span class="list-text"><%= product.description %></span>
		</a>
	</div>
<% end %>
<% if @products.count == 0 %>
	<div class="link-list">Dieser User hat noch keine Produkte eingstellt.</div>
<% end %>

<h2>Tausche</h2>
<% @bargainsProposed.each do |bargain| %>
	<div class="link-list">
		<a href="<%= url_for :action => :show, :controller => :bargains, :id => bargain.id %>">
			<span class="list-head"><%= bargain.product1.name %></span>
			<span class="list-text"><%= bargain.product1quantity %>x</span><span class="list-text">gegen</span><span class="list-text"><%= bargain.product2quantity %>x</span>
			<span class="list-head"><%= bargain.product2.name %></span>
		</a>
	</div>
<% end %>
<% @bargainsAccepted.each do |bargain| %>
	<div class="link-list">
		<a href="<%= url_for :action => :show, :controller => :bargains, :id => bargain.id %>">
			<span class="list-head"><%= bargain.product1.name %></span>
			<span class="list-text"><%= bargain.product1quantity %>x</span><span class="list-text">gegen</span><span class="list-text"><%= bargain.product2quantity %>x</span>
			<span class="list-head"><%= bargain.product2.name %></span>
		</a>
	</div>
<% end %>
<% if @bargainsProposed.count + @bargainsAccepted.count == 0 %>
	<div class="link-list">Dieser User hat noch keinen Tausch durchgef&uuml;hrt.</div>
<% end %>

<% if session[:user] && session[:user].id == @user.id %>
	<%= link_to "Eigenes Profil bearbeiten", edit_user_path(@user) %>
<% end %>
<% if session[:user] && session[:user].id == 1 %>
	<a href="<%= url_for user_destroy_real_path(:id => @user.id) %>">ALS ADMINISTRATOR LÖSCHEN (vorsicht!)</a><br />
	Mail: <%= @user.email %><br />
	Gratisprobe: <%= @user.gotSample ? "ja" : "nein" %>
<% end %>