config/routes.rb
Moerse::Application.routes.draw do

  match		"moerse/home", :as => "home"
  
  post		"bargains/accept"
  match		"moerse/bargains/accept", :as => "acceptBargain"
  post		"bargains/deny"
  match		"moerse/bargains/deny", :as => "denyBargain"
  post		"bargains/repropose"
  match		"moerse/bargains/repropose", :as => "reproposeBargain"
  get		"bargains/destroy"
  match		"moerse/bargains/destroy", :as => "bargain_destroy"
  resources	:bargains, :path => "/moerse/bargains"
  resources	:bargains

  resources	:products, :path => "/moerse/products"
  get		"products/destroy"
  match		"moerse/products/destroy", :as => "product_destroy"
  get		"products/destroy_real"
  match		"moerse/products/destroy_real", :as => "product_destroy_real"
  resources	:products
  
  get		"users/resetPassword"
  post		"users/resetPassword"
  match		"moerse/users/resetPassword", :as => "resetPassword"
  get		"users/dashboard"
  match		"moerse/users/dashboard", :as => "dashboard"
  get		"users/destroy_real"
  match		"moerse/users/destroy_real", :as => "user_destroy_real"
  get		"users/destroy"
  match		"moerse/users/destroy", :as => "user_destroy"
  resources	:users, :path => "/moerse/users"
  resources	:users
  
  get		"sessions/new"
  post		"sessions/create"
  get		"sessions/destroy"
  match		"moerse/sessions/destroy", :as => "logout"
  resources	:sessions, :path => "/moerse/sessions"
  resources	:sessions

  resources	:home, :path => "/moerse/home"
  resources	:home
  
  resources :imprint, :path => "/moerse/imprint"
  resources :imprint
  
  resources :agb, :path => "/moerse/agb"
  resources :agb

  root :to => "home#index"

  
end

app/models/product.rb
class Product < ActiveRecord::Base

	attr_accessible :name, :description, :photo1, :photo2, :photo3, :photo4, :brand, :productClass, :comment, :subject, :weight
	# attr_protected :id, :salt
	
	validate :name, :presence => true, :uniqueness => {:case_sensitive => false}
	
	attr_accessible :photo1, :photo2, :photo3, :photo4
	
	has_attached_file :photo1, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension", :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename"
	validates_attachment_content_type :photo1, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo1, :less_than => 2.megabytes
	
	has_attached_file :photo2, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension", :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename"
	validates_attachment_content_type :photo2, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo2, :less_than => 2.megabytes
	
	has_attached_file :photo3, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension", :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename"
	validates_attachment_content_type :photo3, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo3, :less_than => 2.megabytes
	
	has_attached_file :photo4, :styles => { :thumb  => "130x130", :medium => "500x500", :large =>  "750x750"}, :url => "/moerse/system/:class/:id/:attachment/:style/:basename.:extension", :path => ":rails_root/public/system/:class/:id/:attachment/:style/:filename"
	validates_attachment_content_type :photo4, :content_type => [ 'image/png', 'image/x-png', 'image/jpg', 'image/jpeg', 'image/gif' ], :message => 'Die angegebene Datei ist keine Bilddatei.'
	validates_attachment_size :photo4, :less_than => 2.megabytes
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.find(:all, :conditions => ["inactive != ?", true])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @owningUser = User.find_by_id @product.userId
    @relatedBargainsProposed = Bargain.find(:all, :conditions => {:product1id => @product.id, :status => "1"})
	@relatedBargainsAccepted = Bargain.find(:all, :conditions => {:product2id => @product.id, :status => "1"})
	if @product.views.nil?
		@product.views = 0
	end
	@product.views += 1
	@product.save
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
	@customImages = false
    @relatedBargainsProposed = Bargain.find(:all, :conditions => {:product1id => @product.id, :status => "1"})
	@relatedBargainsAccepted = Bargain.find(:all, :conditions => {:product2id => @product.id, :status => "1"})
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
	@product.inactive = false
	@product.views = 0
	if session[:user].present?
		@product.userId = session[:user].id
	else
		@product.userId = 0
	end
	if @product.save
		redirect_to @product
		flash[:notice] = "Das Produkt wurde erfolgreich erstellt."
	else
		render :new
		flash[:notice] = 'Etwas hat unerwarteterweise nicht geklappt. Bitte versuchen Sie es erneut.'
	end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

	if @product.update_attributes(params[:product])
		redirect_to @product
		flash[:notice] = "Das Produkt wurde erfolgreich aktualisiert."
	else
		render :edit
		flash[:notice] = "Das Produkt existiert nicht (mehr)."
	end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
	@product.inactive = true
	@product.save
    # @product.destroy
	redirect_to products_url
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy_real
    @product = Product.find(params[:id])
    @product.destroy
	redirect_to products_url
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %> 
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label "Beschreibung" %><br />
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label "Marke" %><br />
    <%= f.text_field :brand %>
  </p>
  <p>
    <%= f.label "Produktklasse" %><br />
    <%= f.text_field :productClass %>
  </p>
  
  <p>
    <%= f.label "Kommentar" %><br />
    <%= f.text_field :comment %>
  </p>
  <p>
    <%= f.label "Gewicht" %><br />
    <%= f.text_field :weight, :size => 3, :maxlength => 3 %>
  </p>
  
  <% if @customImages %>
  <p>
    <%= f.label :photo1 %><br />
    <%= f.file_field :photo1 %>
  </p>
  <p>
    <%= f.label :photo2 %><br />
    <%= f.file_field :photo2 %>
  </p>
  <p>
    <%= f.label :photo3 %><br />
    <%= f.file_field :photo3 %>
  </p>
  <p>
    <%= f.label :photo4 %><br />
    <%= f.file_field :photo4 %>
  </p>
  <% end %>
  
  <p>
	<%= submit_tag "abschicken" %>
  </p>
  
<% end %>

app/views/products/edit.html.erb
<h1>Eigenes Produkt bearbeiten!</h1>

<%= render 'form' %>
<p>
	<% if @relatedBargainsProposed.count + @relatedBargainsAccepted.count == 0 %>
		<p><a href="<%= url_for product_destroy_path(:id => @product.id) %>" data-confirm="Sind Sie sich sicher?">Produkt löschen</a> |
	<% else %>
		Dieses Produkt wurde schon getauscht. Sie können es nicht mehr löschen.
	<% end %>
</p>

<%= link_to 'Produkt zeigen', @product %>

app/views/products/index.html.erb
<h1>Alle Produkte!</h1>
<% if session[:user] && session[:user].inactive != "true" %>
	<p><%= link_to 'Produkt erstellen', new_product_path %></p>
<% end %>
<% @products.each do |product| %>
	<div class="link-list">
		<a href="<%= url_for :action => :show, :id => product.id %>">
			<span class="list-head"><%= product.name %></span><br />
			<span class="list-text"><%= product.description[0..100].strip + (product.description.length > 100 ? "... [mehr]" : "") %></span>
		</a>
	</div>
<% end %>
<br />

<% if session[:user] %>
	<% if session[:user].inactive == "true" %>
		<p>Ihr Profil ist inaktiv! Bitte aktivieren Sie es, um wieder Produkte erstellen zu können.</p>
	<% else %>
		<p><%= link_to 'Produkt erstellen', new_product_path %></p>
	<% end %>
<% else %>
	<p>Bitte loggen Sie sich ein um Produkte erstellen zu können!</p>
<% end %>

app/views/products/new.html.erb
<h1>Produkt anlegen!</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %>!</h1>
<%= image_tag "/images/bottles/" + (1..14).to_a.sample.to_s + ".jpg", {:height => 400} %>
<div style="font-size: 1; color: #666666; margin-top: -5px">© Stefan Kaz</div>

<p>
  <span class="list-head">Beschreibung</span><br />
  <%= @product.description %>
</p>

<% if (@product.photo1.present?) %>
	<p><%= image_tag(@product.photo1.url(:thumb)) %></p>
<% end %>

<% if (@product.photo2.present?) %>
	<p><%= image_tag(@product.photo2.url(:thumb)) %></p>
<% end %>

<% if (@product.photo3.present?) %>
	<p><%= image_tag(@product.photo3.url(:thumb)) %></p>
<% end %>

<% if (@product.photo4.present?) %>
	<p><%= image_tag(@product.photo4.url(:thumb)) %></p>
<% end %>

<p>
  <span class="list-head">Marke</span><br />
  <%= @product.brand %>
</p>
<p>
  <span class="list-head">Produktklasse</span><br />
  <%= @product.productClass %>
</p>
<p>
  <span class="list-head">Kommentar</span><br />
  <%= @product.comment %>
</p>
<p>
  <span class="list-head">Gewicht</span><br />
  <%= @product.weight %>
</p>

<p>
	<span class="list-head">Benutzer</span><br />
		<% if @owningUser.present? %>
			<a href="<%= url_for :action => :show, :controller => :users, :id => @owningUser.id %>"><%= @owningUser.name %></a>
		<% else %>
			Kein Benutzer oder Benutzer gelöscht.
	<% end %>
</p>

<h2>Beteiligte Tausche</h2>
	<% @relatedBargainsProposed.each do |bargain| %>
		<div class="link-list">
			gegen
			<span class="list-text"><%= bargain.product2quantity %>x </span>
			<span class="list-head"><a href="<%= url_for :action => :show, :controller => :bargains, :id => bargain.id %>"><%= bargain.product2.name %></a></span>
			<span class="list-text">von </span> <span class="list-head"><%= link_to bargain.owningUser2.name, bargain.owningUser2 %></span>
		</div>
	<% end %>
	<% @relatedBargainsAccepted.each do |bargain| %>
		<div class="link-list">
			gegen
			<span class="list-text"><%= bargain.product1quantity %>x </span>
			<span class="list-head"><a href="<%= url_for :action => :show, :controller => :bargains, :id => bargain.id %>"><%= bargain.product1.name %></a></span>
			<span class="list-text">von </span> <span class="list-head"><%= link_to bargain.owningUser1.name, bargain.owningUser1 %></span>
		</div>
	<% end %>
	<% if @relatedBargainsProposed.count + @relatedBargainsAccepted.count == 0 %>
		<div class="link-list">Mit diesem Produkt wurde bisher nicht erfolgreich gehandelt.</div>
	<% end %>
<br />
<p><%= link_to "Mit diesem Produkt handeln", new_bargain_path %></p>
<p>Diess Produkt wurde bisher <%= @product.views %>x aufgerufen.</p>

<% if session[:user] && (@product.userId == session[:user].id) %>
	<%= link_to "Eigenes Produkt bearbeiten", edit_product_path(@product) %>
	<% if @relatedBargainsProposed.count + @relatedBargainsAccepted.count == 0 %>
		| <a href="<%= url_for product_destroy_path(:id => @product.id) %>" data-confirm="Sind Sie sich sicher?">Produkt löschen</a>
	<% end %>
<% end %>

<% if session[:user] && session[:user].id == 1 %>
	<% if @relatedBargainsProposed.count + @relatedBargainsAccepted.count == 0 %>
		<a href="<%= url_for product_destroy_real_path(:id => @product.id) %>" data-confirm="Sind Sie sich sicher?">ALS ADMINISTRATOR LÖSCHEN (vorsicht!)</a>
	<% end %>
<% end %>